name: sa_env
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - flask-mail
  - flask-migrate
  - flask-socketio
  - flask-sqlalchemy
  - gunicorn
  - pip
  - python
  - pip:
      - flask-cors
      - flask-jwt-extended
      - pyjwt
